test: elasticsearch
password: BR98BO3iztJSxSgfhjdksldlkfehn12345dska2
opensearch_version: 2.12.0

# elasticsearch01:
#   nodetype: cluster_manager
# elasticsearch02:
#   nodetype: data_1
# elasticsearch03:
#   nodetype: data_2