- name: Check all connections 
  hosts: all 

  tasks:
    - name: Node Setup yes
      #ping:
      setup:
      register: node_setup

    - name: display node setup
      debug:
        msg: "{{ node_setup }}"