- name: Check graylog connections 
  hosts: graylog

  tasks:

    - name: display node setup
      debug:
        msg: "{{ test }}"

- name: Check elasticsearch connections 
  hosts: elasticsearch

  tasks:

    - name: display node setup
      debug:
        msg: "{{ test }}"


