graylog_timezone: Europe/Kiev
graylog_version: 5.0
graylog_port: 9000
graylog_root_username: admin
graylog_password_secret: 4M3jfAJcq6eLjPuQIDwL0u420q13EAfgHKb4U4P21L2-yjoIvIsHrZPk0ywHRtKtgDHl6wntpVepxH5la4d3n8cwZxrLXqY0
graylog_root_password_sha2: e5c477a64858b31be3923774a5ec3a05e7fd4087984a6aa986293c73c2d1d872
graylog_database_version: 6.0
graylog_database: graylog
graylog_database_user: graylog
graylog_database_replica_set: rs01
graylog_database_password: Pa$$w0rd
graylog_database_admin_user: admin
graylog_database_admin_password: admin
graylog_database_roles: readWrite,dbAdmin
graylog_database_port: 27017
